export const COLORS = {
  primary: '#00D4FF',
  primaryDark: '#0099CC',
  primaryLight: '#66E5FF',
  secondary: '#7C4DFF',
  secondaryDark: '#651FFF',
  accent: '#00E676',
  danger: '#FF1744',
  warning: '#FF9100',
  success: '#00E676',
  background: '#0A0E21',
  surface: '#151A30',
  surfaceLight: '#1E2345',
  card: '#1A1F3A',
  text: '#FFFFFF',
  textSecondary: '#8892B0',
  textMuted: '#5A6380',
  border: '#2A2F4A',
  white: '#FFFFFF',
  black: '#000000',
  overlay: 'rgba(0,0,0,0.7)',
  battery: {
    excellent: '#00E676',
    good: '#76FF03',
    fair: '#FFD600',
    poor: '#FF9100',
    critical: '#FF1744',
    dead: '#B71C1C',
  },
};

export const BATTERY_STATUS = {
  EXCELLENT: { label: 'Excellent', color: COLORS.battery.excellent, min: 90, icon: 'battery-full' },
  GOOD: { label: 'Good', color: COLORS.battery.good, min: 70, icon: 'battery-three-quarters' },
  FAIR: { label: 'Fair', color: COLORS.battery.fair, min: 50, icon: 'battery-half' },
  POOR: { label: 'Poor', color: COLORS.battery.poor, min: 30, icon: 'battery-quarter' },
  CRITICAL: { label: 'Critical', color: COLORS.battery.critical, min: 15, icon: 'battery-empty' },
  DEAD: { label: 'Dead', color: COLORS.battery.dead, min: 0, icon: 'battery-off' },
};

export const VOLTAGE_RANGES = {
  EXCELLENT: { min: 12.6, max: 12.8, label: 'Fully Charged' },
  GOOD: { min: 12.4, max: 12.59, label: 'Well Charged' },
  FAIR: { min: 12.2, max: 12.39, label: 'Moderately Charged' },
  LOW: { min: 12.0, max: 12.19, label: 'Low Charge' },
  CRITICAL: { min: 11.8, max: 11.99, label: 'Very Low' },
  DEAD: { min: 0, max: 11.79, label: 'Discharged' },
  OVERCHARGED: { min: 12.9, max: 15.0, label: 'Overcharging' },
};

export const SUBSCRIPTION_TIERS = {
  FREE: {
    id: 'free',
    name: 'Free Trial',
    price: 0,
    period: '7 days',
    color: COLORS.textSecondary,
    features: [
      '3 battery scans per day',
      'Basic voltage reading',
      'Simple health percentage',
      'Low battery alerts',
      '7-day history',
      '1 vehicle profile',
      'Basic maintenance tips',
    ],
    limits: { scansPerDay: 3, vehicles: 1, historyDays: 7 },
  },
  BASIC: {
    id: 'basic',
    name: 'Basic',
    price: 14.99,
    period: 'month',
    color: COLORS.primary,
    features: [
      'Unlimited battery scans',
      'Detailed voltage analysis',
      'Cold Cranking Amps (CCA)',
      'All alert types + push notifications',
      '1-year history & trends',
      '3 vehicle profiles',
      'Basic PDF reports',
      'Charging system test',
      'Battery replacement tracker',
      'Seasonal maintenance tips',
      'Email support',
    ],
    limits: { scansPerDay: Infinity, vehicles: 3, historyDays: 365 },
  },
  PRO: {
    id: 'pro',
    name: 'Pro',
    price: 24.99,
    period: 'month',
    color: COLORS.accent,
    popular: true,
    features: [
      'Everything in Free Trial + Basic',
      'Unlimited battery scans',
      'Detailed voltage analysis',
      'Cold Cranking Amps (CCA)',
      'All alert types + push notifications',
      '1-year history & trends',
      '5 vehicle profiles',
      'PDF reports + email delivery',
      'Charging system test',
      'Battery replacement tracker',
      'Temperature impact analysis',
      'Charge cycle tracking',
      'AI battery life prediction',
      'Personalized maintenance tips',
      'Priority email support',
    ],
    limits: { scansPerDay: Infinity, vehicles: 5, historyDays: 365 },
  },
  ADVANCED: {
    id: 'advanced',
    name: 'Advanced',
    price: 39.99,
    period: 'month',
    color: COLORS.secondary,
    features: [
      'Everything in Pro',
      'Unlimited vehicle profiles',
      'Unlimited history',
      'Full PDF reports + auto email',
      'Predictive maintenance alerts',
      'Warranty tracking',
      'Multi-language support',
      '24/7 Priority chat support',
      'Beta feature access',
      'Family sharing (up to 5 accounts)',
    ],
    limits: { scansPerDay: Infinity, vehicles: Infinity, historyDays: Infinity },
  },
};

export const OBD_PIDS = {
  BATTERY_VOLTAGE: '0142',
  BATTERY_SOC: '015B',
  AMBIENT_TEMP: '0146',
  ENGINE_RPM: '010C',
  VEHICLE_SPEED: '010D',
  COOLANT_TEMP: '0105',
  INTAKE_AIR_TEMP: '010F',
  CONTROL_MODULE_VOLTAGE: '0142',
};

export const MAINTENANCE_TIPS = {
  winter: [
    { title: 'Keep Your Battery Warm', desc: 'Use a battery blanket or insulated cover in freezing temperatures.', priority: 'high' },
    { title: 'Short Trips Drain Batteries', desc: 'Take longer drives (20+ min) to allow full recharging.', priority: 'medium' },
    { title: 'Check Terminals for Corrosion', desc: 'Cold weather accelerates corrosion. Clean with baking soda solution.', priority: 'high' },
    { title: 'Test Before Winter Hits', desc: 'Get your battery tested in fall before cold weather arrives.', priority: 'medium' },
    { title: 'Turn Off Accessories', desc: 'Minimize heater, lights, and radio usage when engine is off.', priority: 'low' },
  ],
  summer: [
    { title: 'Heat Kills Batteries', desc: 'High temps cause fluid evaporation. Check electrolyte levels.', priority: 'high' },
    { title: 'Park in Shade', desc: 'Reduce heat exposure to extend battery life.', priority: 'medium' },
    { title: 'Check Charging Voltage', desc: 'Ensure alternator is not overcharging in hot weather.', priority: 'high' },
    { title: 'Clean Battery Terminals', desc: 'Heat accelerates corrosion buildup on terminals.', priority: 'medium' },
    { title: 'Secure Battery Mount', desc: 'Vibration from summer road conditions can damage battery.', priority: 'low' },
  ],
  general: [
    { title: 'Regular Voltage Checks', desc: 'Scan your battery weekly to track health trends.', priority: 'low' },
    { title: 'Clean Connections', desc: 'Ensure tight, corrosion-free cable connections.', priority: 'medium' },
    { title: 'Avoid Deep Discharges', desc: 'Don\'t leave lights or electronics on with engine off.', priority: 'high' },
    { title: 'Drive Regularly', desc: 'Batteries self-discharge when sitting. Drive at least once a week.', priority: 'medium' },
    { title: 'Check Age', desc: 'Most batteries last 3-5 years. Track your battery age.', priority: 'high' },
    { title: 'Inspect for Swelling', desc: 'A bulging battery case indicates failure. Replace immediately.', priority: 'high' },
  ],
};

export const SCREEN_NAMES = {
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOME: 'Home',
  SCAN: 'Scan',
  BATTERY_DETAIL: 'BatteryDetail',
  HISTORY: 'History',
  TIPS: 'Tips',
  REPORTS: 'Reports',
  SUBSCRIPTION: 'Subscription',
  SETTINGS: 'Settings',
  VEHICLE_MANAGER: 'VehicleManager',
};
